In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Bracket indexing and selection

It is very simple to pick one or more elements of an array if you know list indexing and slicing.
It will easier for us to understand. It uses bracket notation and colon for slicing and indexing.

In [5]:
# lets look at some examples

arr[2]

# this is output the value which is at index 2 . Remember the indexing starts with '0' 
# which means when memory allocation starts with index 0


2

In [6]:
arr[0]

0

In [7]:
# lets say we change our array and try on the new array
arr_1 = np.arange(25,51)

In [8]:
arr_1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [9]:
arr_1[0]

25

In [10]:
arr_1[8] # now you can see and understand better with this and the above examples.

33

In [11]:
arr[0:5] # we can do indexing in a range so here you can see the it has sliced and given us the values from index "0" upto "5" 
# remember index starts with "0" it has given 5 values not including the value at index 5 

array([0, 1, 2, 3, 4])

In [12]:
arr[2:8] # from the index value at 2 upto 8 not including the value at index 8 

array([2, 3, 4, 5, 6, 7])

In [13]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
arr[-1]

10

In [15]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[-5:]

array([ 6,  7,  8,  9, 10])

# Broadcasting

 Numpy arrays have broadcasting as one of its dynamic feature which makes it different from list
 let us see with some exmaples

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:

arr[0:5]=100 # when we do this it replaces all the sliced values with 100 and we would be able to see the change in arr

In [19]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
# let's reset our arr variable and let's see an important feature 

In [21]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = arr[0:6]

In [24]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
# now let's see 
slice_of_arr[:] = 100

In [26]:
# now let's first check slice_of_arr and then check the original arr 

In [27]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [28]:
# see all the values have been changed to 100 now let's check arr

In [29]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [30]:
# so here we see that it has also made the changes in the original array that's the important point to note while dealing 
# with broadcasting in array
# what this means is the data is not copied(in slice_of_array) its actually an actual view of the original array (arr)
# the reason numpy does that is to avoid memory issues with very large arrays meaning numpy is not going to set 
#copies of arrays automatically.
# if you actually want a copy not a reference to the original array what you can do is you can specifically specify copy


to make a copy i can create a new variable by using copy method of the array to indicate that i want a copy

In [31]:
arr_copy = arr.copy()

In [32]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [33]:
# now if do a brodcasting on this arr_copy it will not change anything on the original array let's see
arr_copy[0:6]=99

In [34]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [36]:
# you can clearly see now the difference

# Indexing a 2D array (matrices)
The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [6]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [7]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
# let's index a row 
arr_2d[0]

array([ 5, 10, 15])

In [40]:
arr_2d[-1]

array([35, 40, 45])

In [41]:
arr_2d[1]

array([20, 25, 30])

In [42]:
arr_2d[2]

array([35, 40, 45])

In [43]:
# now let's index column
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr_2d[:,0] # this is the way you can just index only the column 

array([ 5, 20, 35])

In [9]:
arr_2d[:,1]

array([10, 25, 40])

In [45]:
arr_2d[:,2]

array([15, 30, 45])

In [46]:
# lets try to slice different ways to index subsections of our 2D array (matrices)
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [47]:
arr_2d[1:,0]

array([20, 35])

In [52]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# conditional selection

In [48]:
arr_2d > 5

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [49]:
arr_2d[arr_2d>5]

array([10, 15, 20, 25, 30, 35, 40, 45])

In [51]:
arr_2d[1:,(0,2)] # great this is another way to do it 

array([[20, 30],
       [35, 45]])

In [52]:
arr_2d[1:,(0,2)]>20

array([[False,  True],
       [ True,  True]], dtype=bool)



VisibleDeprecationWarning: boolean index did not match indexed array along dimension 1; dimension is 2 but corresponding boolean dimension is 1

https://stackoverflow.com/a/34296620/901925

I think this is something new in numpy 1.10, and is the result of using boolean index that is shorter than array. I don't have that version installed so can't give an example. But in an earlier numpy

In [667]: x=np.arange(10)
In [668]: ind=np.array([1,0,0,1],bool)
In [669]: ind
Out[669]: array([ True, False, False,  True], dtype=bool)
In [670]: x[ind]
Out[670]: array([0, 3])
runs ok, even though ind is shorter than x. It effectively pads ind with False. I think newer versions continue to do the calculation, but issue this warning. I need to find a commit that changed this or a SO question that discusses it.

It is possible to suppress warnings - see the side bar. But you really should check the shape of the offending arrays. Do they match, or is the boolean index too short? Can you correct that?

Github discussion

https://github.com/numpy/numpy/issues/4980 Boolean array indexing fails silently #4980

Pull request

https://github.com/numpy/numpy/pull/4353 DEP: Deprecate boolean array indices with non-matching shape #4353

To suppress the warning use something like:

import warnings
warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning) 
you may have to tweak the category name to get it right.