In [5]:
import numpy
numpy.version.version

'1.14.3'

In [6]:
import numpy as np

In [3]:
my_list = [1,2,3,4]

In [4]:
np.array(my_list)

array([1, 2, 3, 4])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:




np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

 Built in Methods
there are lots of methods to generate arrays

 1 arange
returns evenly spaced values within a given interval

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

here we can note that if we have given an interval as 0 to 10 10 will not be included in the final output
let us see some more example

In [11]:
np.arange(5,61)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60])

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(80)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [5]:
np.arange(0,11),np.arange(0,20,1)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19])]

In [14]:
np.arange(0,0)

array([], dtype=int32)

In [15]:
my_list1 = [ "chatur", 3, "idiots"]

In [16]:
np.array(my_list1)

array(['chatur', '3', 'idiots'],
      dtype='<U6')

In [17]:
my_list1 = ["chatur", "rama", "linga"]

In [18]:
np.array(my_list1)

array(['chatur', 'rama', 'linga'],
      dtype='<U6')

zeros and ones 
generate arrays of zeros and ones

In [19]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [20]:
np.ones(6)

array([ 1.,  1.,  1.,  1.,  1.,  1.])

In [21]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
np.ones((6,5)) # it wil create matrix of one on 6 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace 
return evenly spaced numbers over a specified interval

In [23]:
np.linspace(5,10,7)

array([  5.        ,   5.83333333,   6.66666667,   7.5       ,
         8.33333333,   9.16666667,  10.        ])

In [24]:
np.linspace(-1,0,10)

array([-1.        , -0.88888889, -0.77777778, -0.66666667, -0.55555556,
       -0.44444444, -0.33333333, -0.22222222, -0.11111111,  0.        ])

In [25]:
np.linspace(10,1000,3)

array([   10.,   505.,  1000.])

In [26]:
np.linspace(10,1000,2)

array([   10.,  1000.])

In [27]:
np.linspace(10,1000,1)

array([ 10.])

# eye
creates an indentity matrix below are some examples
All the elements of the matrix apart from the diagonal are zero.
the indentity matrix for any matrix is going to be a square matrix.

In [28]:
np.eye(3,2)

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  0.]])

In [29]:
np.eye(2,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [30]:
np.eye(3,3) # this is a correct way to represent an identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# Random
Numpy also has various ways with which we can create array of random numbers (random number arrays)


the first method is # rand 
which Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

# rand

#what is a unifrom distribution
#a uniform distribution is a set of variables that all have the exact same possibility of happening. 
#This uniform distribution, when displayed as a bar graph, has the exact same height of each bar and a standard number of bars. 
#In this way, it typically looks like a rectangle and therefore is often described as the rectangle distribution. 
#If you think about the possibility of pulling each suit's face card from a deck of playing cards, there is a random yet equal chance of pulling the jack of hearts as there is for pulling the king of spades.
 In statistics, a type of probability distribution in which all outcomes are equally likely.
#A deck of cards has a uniform distribution because the likelihood of drawing a heart, a club, a diamond or a spade is equally likely.
#A coin also has a uniform distribution because the probability of getting either heads or tails in a coin toss is the same.


In [31]:
np.random.rand(5) # the number 5 is how many numbers it will generate between 0 and 1 from a uniform distribution 



array([ 0.56870054,  0.76046803,  0.35411211,  0.18496201,  0.6085879 ])

In [32]:
np.random.rand(5,5)

array([[ 0.31386022,  0.63004937,  0.07647504,  0.20820138,  0.15864598],
       [ 0.19521628,  0.10909564,  0.43112124,  0.25154938,  0.34070416],
       [ 0.59030893,  0.95644554,  0.90498118,  0.77013231,  0.0248718 ],
       [ 0.30378221,  0.91721596,  0.92099553,  0.14380567,  0.190043  ],
       [ 0.51670568,  0.24197624,  0.28195057,  0.92358923,  0.60177798]])

In [33]:
np.random.rand(6,5)

array([[ 0.1136537 ,  0.01215439,  0.78414276,  0.62424806,  0.02848931],
       [ 0.82528794,  0.2733241 ,  0.21985376,  0.31474875,  0.64505004],
       [ 0.55133332,  0.81139683,  0.19625143,  0.05690624,  0.59467297],
       [ 0.56196531,  0.68757863,  0.00723548,  0.74788805,  0.52617647],
       [ 0.72373148,  0.07394714,  0.62269953,  0.24690499,  0.62988772],
       [ 0.50060331,  0.06018511,  0.13474597,  0.62815463,  0.36047593]])

In [34]:
np.random.rand(3,5)

array([[ 0.19490887,  0.70684222,  0.02047275,  0.38771699,  0.74301288],
       [ 0.04106055,  0.01317653,  0.21918184,  0.41976412,  0.76338513],
       [ 0.76833516,  0.16036408,  0.31899139,  0.81498564,  0.72825245]])

In [35]:
np.random.rand(1,1) # matrix with one row and one column

array([[ 0.76085595]])

# randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform
Properties of normal distribution :The standard normal distribution is a normal distribution with a:
mean of 0,
standard deviation of 1.

A normal distribution is a continuous probability distribution for a random variable x. The graph of a normal
distribution is called the normal curve, which has all of the following properties:
1. The mean, median, and mode are equal.
2. The normal curve is bell-shaped and is symmetric about the mean.
3. The total area under the curve is equal to one.
4. The normal curve approaches, but never touches, the x-axis.
5. Between µ − σ and µ + σ the graph is concave down and elsewhere the graph is concave up. The points at
which the graph changes concavity are called inflection points

In [36]:
np.random.randn(4) # again the the number 4 is the number of values it will generate.

array([ 1.67427244, -0.90302583, -1.00092625,  1.06226877])

In [37]:
np.random.randn(6,4)

array([[ 1.29402954, -2.23890789, -0.13174897, -0.28896542],
       [-0.44387226,  0.77014545,  1.28181379,  0.45781549],
       [-0.28081864,  0.25586636, -1.29418404,  0.84393632],
       [-1.41599629, -0.15748644,  0.42846773,  2.43360404],
       [ 1.1733322 ,  0.29101576,  0.37752698,  1.20736324],
       [-1.35813665, -0.40765548,  0.21430258, -0.20219355]])

# randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [38]:
np.random.randint(1,10) # it will output a random integer in this case the default number of values it wil output is one 
#if you dont specify number of values you want in your output

2

In [39]:
np.random.randint(10,100,10) # it will output ten integers between 10 to 100

array([37, 84, 99, 91, 17, 42, 98, 75, 97, 56])

# Array Attributes and Methods

here we will see some useful methods and attributes of array

In [8]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr

array([26, 39, 26,  9, 45, 33, 26,  8, 12, 19])

#  Reshape
Returns an array containing the same data with a new shape.

In [10]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
# one important thing elements in the array should match the arguments you pass in the array.
#in the above case it was (5,5) and there were 25 elements.

In [12]:
arr.reshape(5,4) # here is the example of what happens

ValueError: cannot reshape array of size 25 into shape (5,4)

In [14]:
ranarr.reshape(5,2)

array([[32, 10],
       [ 2, 15],
       [36,  3],
       [29, 19],
       [17, 47]])

# max,min,argmax,argmin
These are useful methods for finding max or min values. 

argmax and argmin are used for finding index location of the max value and the minimum value.

In [49]:
ranarr.max()

45

In [50]:
ranarr.min()

8

In [51]:
ranarr.argmax()

4

In [52]:
ranarr.argmin()

7

# Shape 

In [54]:
# shape is used for getting the shape of array, whether it is one dimensional or two dimensional

In [55]:
arr.shape

(25,)

In [56]:
# if we want we can reshape it with our reshape method

In [57]:
ranarr.shape

(10,)

In [ ]:
# this marks the end of array first chapter.

NumPy mgrid vs. meshgrid
Louis Tiao 2015-10-30 16:00 0 Comments Source
The meshgrid function is useful for creating coordinate arrays to vectorize function evaluations over a grid. Experienced NumPy users will have noticed some discrepancy between meshgrid and the mgrid, a function that is used just as often, for exactly the same purpose. What is the discrepancy, and why does a discrepancy even exist when "there should be one - and preferably only one - obvious way to do it." [1]

First, recall that meshgrid behaves as follows:

>>> import numpy as np
>>> x1, y1 = np.meshgrid(np.arange(1, 11, 2), np.arange(-12, -3, 3))
>>> x1
array([[1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9]])
>>> y1
array([[-12, -12, -12, -12, -12],
       [ -9,  -9,  -9,  -9,  -9],
       [ -6,  -6,  -6,  -6,  -6]])
If you have used NumPy for a while or are familiar enough with how Broadcasting works, you will have realized that meshgrid is actually superfluous for NumPy arrays, and that it is actually just an implementation of MATLAB's meshgrid, probably to cater to users coming from a MATLAB background.

Observe the behavior of mgrid, which essentially returns the transpose of meshgrid:

>>> x2, y2 = np.mgrid[1:11:2, -12:-3:3]
>>> x2
array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7],
       [9, 9, 9]])
>>> y2
array([[-12,  -9,  -6],
       [-12,  -9,  -6],
       [-12,  -9,  -6],
       [-12,  -9,  -6],
       [-12,  -9,  -6]])
>>> np.all(x1 == x2.T)
True
>>> np.all(y2 == y2.T)
True
Note this this order is actually more natural, since mgrid just fleshes out the open (not fleshed out) grids given by ogrid by broadcasting them to form dense grids, i.e.

>>> a, b = np.ogrid[1:11:2, -12:-3:3]
>>> a
array([[1],
       [3],
       [5],
       [7],
       [9]])
>>> b
array([[-12,  -9,  -6]])
and the 5x1 array a is broadcasted with the 1x3 array b to form two 5x3 arrays

>>> x2, y2 = np.broadcast_arrays(a, b)
>>> x2
array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7],
       [9, 9, 9]])
>>> y2
array([[-12,  -9,  -6],
       [-12,  -9,  -6],
       [-12,  -9,  -6],
       [-12,  -9,  -6],
       [-12,  -9,  -6]])
which behaves exactly the same way as mgrid. Note that you seldom have to broadcast arrays explicitly, let alone use functions like mgrid or meshgrid, since all arithmetic operations on NumPy arrays already perform broadcasting implicitly. E.g.

>>> x2 + y2
array([[-11,  -8,  -5],
       [ -9,  -6,  -3],
       [ -7,  -4,  -1],
       [ -5,  -2,   1],
       [ -3,   0,   3]])
>>> a + b
array([[-11,  -8,  -5],
       [ -9,  -6,  -3],
       [ -7,  -4,  -1],
       [ -5,  -2,   1],
       [ -3,   0,   3]])
Finally, if for some reason you must have output like that of meshgrid, just use mgrid with the arguments and unpacking targets reversed.

>>> y3, x3 = np.mgrid[-12:-3:3, 1:11:2]
>>> x3
array([[1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9],
       [1, 3, 5, 7, 9]])
>>> y3
array([[-12, -12, -12, -12, -12],
       [ -9,  -9,  -9,  -9,  -9],
       [ -6,  -6,  -6,  -6,  -6]])
>>> np.all(x1 == x3)
True
>>> np.all(y1 == y3)
True
Of course, if you are using np.linspace instead of np.arange, then you're better off sticking with np.meshgrid.

[1]	PEP20 - The Zen of Python (https://www.python.org/dev/peps/pep-0020/)
Further Reading
http://stackoverflow.com/questions/12402045/mesh-grid-functions-in-python-meshgrid-mgrid-ogrid-ndgrid

More elegant way to create a 2D matrix in Python [duplicate]

Ask Question


up vote
13
down vote
favorite
3
Possible Duplicate:
How to initialize a two-dimensional array in Python?
I have always written this part of code in this way: every time I need it, I use this python code:

for x in range(8):
        a.append([])
        for y in range(8):
            a[x].append(0)
However, I'd like to know if there's a way to beautify this piece of code. I mean, how do you create a bidimensional matrix in python, and fill it with 0?

python loops matrix
shareimprove this question
edited May 23 at 12:34

Community♦
11
asked Dec 10 '11 at 17:15

user1068051
921211
marked as duplicate by senderle, Junuxx, Andy Hayden, Chris Gerken, Mark Nov 9 '12 at 0:43

This question has been asked before and already has an answer. If those answers do not fully address your question, please ask a new question.

  	 	
this problem is of declaring and initializing two dimensional array is explained nicely here – gaurav Dec 10 '11 at 17:22
add a comment
4 Answers
active oldest votes
up vote
16
down vote
accepted
Use nested list comprehensions:

a = [[0 for y in range(8)] for x in range(8)]
which is eqivalent to

a = []
for x in range(8):
    row = []
    for y in range(8):
        row.append(0)
    a.append(row)
shareimprove this answer
edited Feb 9 '15 at 19:38
answered Dec 10 '11 at 17:16

unutbu
446k718901002
add a comment


up vote
3
down vote
Try this:

a = [[0]*8 for _ in xrange(8)]
It uses list comprehensions and the fact that the * operator can be applied to lists for filling them with n copies of a given element.

Or even better, write a generic function for returning matrices of a given size:

# m: number of rows, n: number of columns
def create_matrix(m, n):
    return [[0]*n for _ in xrange(m)]

a = create_matrix(8, 8)
shareimprove this answer