In [1]:
import numpy as np


In [2]:
arr=np.arrange(0,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [3]:
import numpy as np

In [4]:
my_list=[0,1,2,3,4,5,6]

In [5]:
my_list

[0, 1, 2, 3, 4, 5, 6]

In [6]:
np.array(my_list)

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
my_matrix= [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
my_matrix1=[[1,2,3],[4,5]]

In [16]:
my_matrix1

[[1, 2, 3], [4, 5]]

In [17]:
np.array(my_matrix1)

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [18]:
my_matrix2=[[5,6,7,8,],[9,10,11],[12,13,14]]

In [19]:
my_matrix2

[[5, 6, 7, 8], [9, 10, 11], [12, 13, 14]]

In [20]:
np.array(my_matrix2)

array([list([5, 6, 7, 8]), list([9, 10, 11]), list([12, 13, 14])],
      dtype=object)

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(45,80)

array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79])

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
np.arange(6,10)

array([6, 7, 8, 9])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,11),np.arange(0,20,1)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]))

In [33]:
np.arange(0,17),np.arange(3,30,2)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),
 array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]))

In [34]:
my_list1 = [ "chatur", 3, "idiots"]

In [35]:
my_list1

['chatur', 3, 'idiots']

In [37]:
np.array(my_list1)

array(['chatur', '3', 'idiots'], dtype='<U6')

In [38]:
my_list1 = ["chatur", "rama", "linga"]

In [44]:
ch('A')

NameError: name 'ch' is not defined

In [45]:
ord('A')

65

In [46]:
ch('a')

NameError: name 'ch' is not defined

In [47]:
ord('a')

97

In [48]:
my_list1 = ["chatur", "rama", "linga"]

In [49]:
my_list1

['chatur', 'rama', 'linga']

In [51]:
np.array(my_list1)

array(['chatur', 'rama', 'linga'], dtype='<U6')

In [54]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.ones((6,5))# it creates matrix of 6*5 and the elments remain 1 for all

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.zeros((4,6)) # It creates matrix of 4*6 and element remain 0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [60]:
np.linspace(1,10,4) # it will give value at absolute diffrence , starting will be 1 , ending will be 10 and no of value between 1 and 10 will be 4

array([ 1.,  4.,  7., 10.])

In [62]:
np.linspace(-5,45,17)

array([-5.   , -1.875,  1.25 ,  4.375,  7.5  , 10.625, 13.75 , 16.875,
       20.   , 23.125, 26.25 , 29.375, 32.5  , 35.625, 38.75 , 41.875,
       45.   ])

In [63]:
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [64]:
np.eye(3,2)   # create matrix in which 1 is in diagonal

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [65]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.random.rand(5)

array([0.70937123, 0.44429536, 0.33387275, 0.31581034, 0.19992745])

In [67]:
np.random(67)

TypeError: 'module' object is not callable

In [70]:
np.eye(5,9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [71]:
np.random.rand(6)

array([0.23857706, 0.19558431, 0.66346071, 0.13009601, 0.61001327,
       0.75941204])

In [72]:
np.linspace(6,20,12)

array([ 6.        ,  7.27272727,  8.54545455,  9.81818182, 11.09090909,
       12.36363636, 13.63636364, 14.90909091, 16.18181818, 17.45454545,
       18.72727273, 20.        ])

In [74]:
np.linspace(5,10,7)

array([ 5.        ,  5.83333333,  6.66666667,  7.5       ,  8.33333333,
        9.16666667, 10.        ])

In [77]:
np.random.randn(3,5)

array([[ 0.03101919, -0.31845337, -0.13128847, -0.04627224, -2.15506842],
       [ 0.12476061, -1.04025018,  0.40805161,  0.33833998,  0.22283897],
       [-1.10418012, -0.92060604, -0.11674812, -1.75465771,  1.25796959]])

In [78]:
np.array(34)

array(34)

In [79]:
np.arange(34)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [129]:
arr=np.arange(34)
ranarr = np.random.randint(0,50,10)

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [130]:
ranarr

array([ 7,  2, 11, 32, 23, 17, 48,  6, 43,  3])

In [131]:
arr=np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [114]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
ranarr.reshape(5,2)

array([[ 7,  2],
       [11, 32],
       [23, 17],
       [48,  6],
       [43,  3]])

In [134]:
ranarr.argmax()

6

In [135]:
ranarr.argmin()

1

In [136]:
ranarr.max()

48

In [137]:
ranarr

array([ 7,  2, 11, 32, 23, 17, 48,  6, 43,  3])

In [138]:
ranarr.min()

2

In [139]:
arr.shape()

TypeError: 'tuple' object is not callable

In [140]:
ranarr.shape()

TypeError: 'tuple' object is not callable

In [141]:
arr+arr # it is used to add the array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [142]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [143]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [144]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [145]:
arr/arr

C:\Users\NEW\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [146]:
1/arr

C:\Users\NEW\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [147]:
arr**3   # cube of array

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375], dtype=int32)

In [148]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [149]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [151]:
np.max(arr)

15

In [152]:
np.min(arr)

0

In [153]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [154]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791])

In [155]:
np.tan(arr)

array([ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
        1.15782128e+00, -3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
       -6.79971146e+00, -4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
       -6.35859929e-01,  4.63021133e-01,  7.24460662e+00, -8.55993401e-01])

In [157]:
np.log(arr)

C:\Users\NEW\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 ])

In [160]:
arr=np.arange(10)

In [161]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
arr[0]

0

In [163]:
arr[-1]

9

In [164]:
arr[0:5] # it gives value from 0 to 5 from the array

array([0, 1, 2, 3, 4])

In [166]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [168]:
arr[4:10]

array([4, 5, 6, 7, 8, 9])

In [171]:
arr[4:8]

array([4, 5, 6, 7])

In [172]:
arr[:3]

array([0, 1, 2])

In [173]:
arr[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [174]:
arr[3:4]

array([3])

In [175]:
arr[-1]

9

In [176]:
arr[-10]

0

In [177]:
arr[0]

0

In [178]:
arr[9]

9

In [182]:
arr[4:4]

array([], dtype=int32)

In [183]:
arr[-5:]

array([5, 6, 7, 8, 9])

In [184]:
arr[:-5]

array([0, 1, 2, 3, 4])

In [185]:
arr[0:3]=100

In [186]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [187]:
arr[3:4]=200

In [188]:
arr

array([100, 100, 100, 200,   4,   5,   6,   7,   8,   9])

In [189]:
slice_of_arr=arr[3:4]

In [191]:
slice_of_arr

array([200])

In [192]:
neha=arr[-1:]

In [193]:
neha

array([9])

In [194]:
arr

array([100, 100, 100, 200,   4,   5,   6,   7,   8,   9])

In [195]:
arr[:]

array([100, 100, 100, 200,   4,   5,   6,   7,   8,   9])

In [196]:
arr[:]=600

In [197]:
arr

array([600, 600, 600, 600, 600, 600, 600, 600, 600, 600])

In [198]:
arr_copy=arr.copy()

In [199]:
arr_copy

array([600, 600, 600, 600, 600, 600, 600, 600, 600, 600])

In [200]:
arr_copy[-1]=100

In [201]:
arr_copy

array([600, 600, 600, 600, 600, 600, 600, 600, 600, 100])

In [202]:
arr_copy[:5]=45

In [203]:
arr_copy

array([ 45,  45,  45,  45,  45, 600, 600, 600, 600, 100])

In [204]:
arr

array([600, 600, 600, 600, 600, 600, 600, 600, 600, 600])

In [206]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [207]:
arr

array([600, 600, 600, 600, 600, 600, 600, 600, 600, 600])

In [208]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [209]:
arr_2d[0]

array([1, 2, 3])

In [211]:
arr_2d[-1]

array([7, 8, 9])

In [212]:
arr_2d[2]

array([7, 8, 9])

In [213]:
arr_2d[2][2]

9

In [214]:
arr_2d[-1][0]

7

In [215]:
arr_2d[1][1]

5

In [216]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [218]:
arr_2d[:,0] # used to slice first column

array([1, 4, 7])

In [219]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [220]:
arr_2d>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [223]:
arr_2d[arr_2d>5]

array([6, 7, 8, 9])

In [227]:
arr_2d[1:,(0,2)]

array([[4, 6],
       [7, 9]])

In [229]:
arr_2d[2:,(1,2)]

array([[8, 9]])

In [230]:
arr_2d[2:,(1,2)]>10

array([[False, False]])

In [232]:
arr_2d[1:,(0,2)]<0

array([[False, False],
       [False, False]])

In [236]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [242]:
np.linspace(0.00,0.99,100)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [243]:
np.linspace(0.01,1.00,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [244]:
np.random.rand(100)

array([0.44425599, 0.06995316, 0.42102115, 0.85028194, 0.52391861,
       0.52355003, 0.51219252, 0.64102812, 0.7312839 , 0.89548588,
       0.121517  , 0.32005733, 0.18100856, 0.97871078, 0.74066102,
       0.31212501, 0.25639234, 0.61677235, 0.457702  , 0.26188717,
       0.22403255, 0.94208652, 0.80590825, 0.55477937, 0.18508338,
       0.03765229, 0.23640279, 0.26431912, 0.42008337, 0.45858113,
       0.72737575, 0.68531109, 0.39766731, 0.93154444, 0.69209809,
       0.36000849, 0.90869023, 0.92170142, 0.63036551, 0.26633932,
       0.18484118, 0.65961608, 0.41497903, 0.2031779 , 0.22458215,
       0.69247079, 0.5520023 , 0.54313019, 0.83096511, 0.25680814,
       0.91011797, 0.4377937 , 0.33209204, 0.63265208, 0.64603843,
       0.64335562, 0.19356772, 0.58874621, 0.15600321, 0.89603579,
       0.82575134, 0.1050523 , 0.25707431, 0.96639265, 0.04774023,
       0.69587613, 0.29230192, 0.52574026, 0.85302683, 0.76786474,
       0.71461955, 0.12548634, 0.31302938, 0.81045015, 0.86280

In [246]:
np.random.randint(0.01,20,100)

array([ 7,  8, 18,  6,  2,  8, 15,  7, 13, 16,  7, 14,  4,  0, 12, 10, 14,
        6, 10, 10, 18,  5, 11, 17,  4,  5,  4,  3, 13, 16,  5,  1,  5,  9,
        2,  0, 19,  4,  8, 10, 11, 17,  1, 14, 14, 11, 18,  4,  5, 19,  7,
        3, 12,  4,  3, 19, 10, 10,  3,  8, 19,  0,  3,  2, 15, 10, 19, 13,
        7, 15, 17, 14, 17,  2,  3, 10, 10, 15, 15,  5, 14, 19,  9, 18, 10,
       18,  2,  4,  5, 19, 14,  5, 13, 18,  8,  6, 12,  8, 18, 15])

In [248]:
np.random(0,1,20)

TypeError: 'module' object is not callable

In [249]:
np.random.rand(20)

array([3.49154303e-01, 3.53176041e-01, 9.93277085e-01, 7.86543030e-01,
       8.32140394e-01, 2.79800563e-01, 4.68370220e-01, 4.10896058e-01,
       9.87210836e-01, 8.06999544e-01, 3.04939486e-01, 5.56192839e-01,
       6.73133285e-01, 6.60321848e-01, 4.26002144e-01, 4.12630173e-01,
       8.98864818e-01, 4.91965673e-02, 2.12080413e-04, 3.04035224e-01])

In [252]:
np.random(0,20,13)

TypeError: 'module' object is not callable

In [253]:
import numpy as np
np.random(20)

TypeError: 'module' object is not callable

In [254]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [255]:
mat[1:,(0,2)]

array([[ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [258]:
mat[2:,(1,2,3,4)]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [264]:
mat[3:4]

array([[16, 17, 18, 19, 20]])

In [265]:
mat[3:4]

array([[16, 17, 18, 19, 20]])

In [266]:
mat[3,4]

20

In [267]:
mat[1]

array([ 6,  7,  8,  9, 10])

In [268]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [269]:
mat[:1]

array([[1, 2, 3, 4, 5]])

In [273]:
slice = mat[2][2]

slice

13

In [274]:
mat[3][4]

20

In [275]:
mat[4]

array([21, 22, 23, 24, 25])

In [297]:
slice=mat[3:]
slice

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [298]:
np.sum(mat)

325

In [299]:
np.std(mat)

7.211102550927978

In [300]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [316]:
mat[0:,3:1]

array([], shape=(5, 0), dtype=int32)

In [317]:
mat+mat

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [321]:
np.column_stack(mat)

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [323]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [327]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [330]:
np.arange(1,22,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [345]:
arr=[1,2,4,6,8,9,12,17,21,22]
arr1=[1,2,4,6,8,12,17,21,400]

In [332]:
arr

[1, 2, 4, 6, 8, 9, 12, 17, 21, 22]

In [333]:
arr1

[1, 2, 4, 6, 8, 12, 17, 21, 400]

In [334]:
type(arr)

list

In [335]:
np.array(arr)

array([ 1,  2,  4,  6,  8,  9, 12, 17, 21, 22])

In [346]:
np.array(arr1)

array([  1,   2,   4,   6,   8,  12,  17,  21, 400])

In [337]:
np.mean(arr)

10.2

In [347]:
np.mean(arr1)

52.333333333333336

In [339]:
np.median(arr)

8.5

In [348]:
np.median(arr1)

8.0

ValueError: invalid number of arguments

In [350]:
import numpy as np
import pandas as pd

In [ ]:
diabetes_df=pd.read_csv("C:\Users\NEW")